version: "3.7"

services:
  api:
    depends_on:
      - db
    image: api-salary
    restart: always
    labels:
      service: "api-salary"
    environment:
      DB_NAME: ${DB_NAME}
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: 3306

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  migration:
    image: flyway/flyway:7.12
    volumes:
      - ./flyway/sql:/flyway/sql
    depends_on:
      - db
    environment:
      FLYWAY_URL: jdbc:mysql://db:3306/${DB_NAME}
      FLYWAY_USER: ${DB_USER}
      FLYWAY_PASSWORD: ${DB_PASSWORD}
      FLYWAY_CONNECT_RETRIES: 100
    command: migrate

  nginx:
    build:
      context: ./nginx
    environment:
      NGINX_EMAIL: ${NGINX_EMAIL}
      NGINX_HOST: ${NGINX_HOST}
    links:
      - api:api
    depends_on:
      - api
    restart: always
    ports:
      - "80:80"
      - "443:443"



