version: 2
jobs:
  build:
    docker:
      - image: cimg/openjdk:15.0
    steps:
      - checkout
      - run:
          name: Format, test and build
          command: |
            java --version
            ./gradlew --version
            ./gradlew clean test

